In [1]:
#Importing Libraries

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
#Reading the dataset

mem=pd.read_csv(r"D:\Intern Work\LetsGrowMore\Music Recommendation\kkbox-music-recommendation-challenge\members.csv")
subm=pd.read_csv(r"D:\Intern Work\LetsGrowMore\Music Recommendation\kkbox-music-recommendation-challenge\sample_submission.csv",nrows=20000)
song_info=pd.read_csv(r"D:\Intern Work\LetsGrowMore\Music Recommendation\kkbox-music-recommendation-challenge\song_extra_info.csv",nrows=20000)
song=pd.read_csv(r"D:\Intern Work\LetsGrowMore\Music Recommendation\kkbox-music-recommendation-challenge\songs.csv",nrows=20000)
train=pd.read_csv(r"D:\Intern Work\LetsGrowMore\Music Recommendation\kkbox-music-recommendation-challenge\train.csv",nrows=20000)
test=pd.read_csv(r"D:\Intern Work\LetsGrowMore\Music Recommendation\kkbox-music-recommendation-challenge\test.csv")

In [3]:
mem.head(25)

,msno,city,bd,gender,registered_via,registration_init_time,expiration_date
0,XQxgAYj3klVKjR3oxPPXYYFp4soD4TuBghkhMTD4oTw=,1,0,NaN,7,20110820,20170920
1,UizsfmJb9mV54qE9hCYyU07Va97c0lCRLEQX3ae+ztM=,1,0,NaN,7,20150628,20170622
2,D8nEhsIOBSoE6VthTaqDX8U6lqjJ7dLdr72mOyLya2A=,1,0,NaN,4,20160411,20170712
3,mCuD+tZ1hERA/o5GPqk38e041J8ZsBaLcu7nGoIIvhI=,1,0,NaN,9,20150906,20150907
4,q4HRBfVSssAFS9iRfxWrohxuk9kCYMKjHOEagUMV6rQ=,1,0,NaN,4,20170126,20170613
5,zgPOEyUn5a/Fvuzb3m69ajzxjkbblVtObglW89FzLdo=,13,43,female,9,20120703,20171006
6,Sw9AT8QoR4wWiNUqHZUH6g5ahzGUx4lo1g+Y3xE2f2M=,1,0,NaN,4,20160326,20160329
7,pg6bT2XZkSP1TDBy4qn3HBPY/HffKQ/bg8WIISQYBSY=,1,0,NaN,7,20160130,20170930
8,kfk1AdTNH2dNqF5LzIs4e0vwGPejw2jrnFjJlcYnEgk=,1,0,NaN,7,20110111,20170930
9,tscijwx4dbEp0NXGl+iFtHJ8zrj+TkcMrduOQk9t+gE=,1,0,NaN,7,20160217,20170613
10,GoFYKhcq8Q5Gjz1M5L0azHZOhcY+Za/T7fRqIGgBuYA=,12,28,male,9,20060531,20170816
11,Hiw71XZQSoEe1I7pBhPWi3kIrP7Ss7pwExZgtqFmtYw=,1,0,NaN,7,20150909,20170909
12,V6QgFYHgsfZ2G6hFz1z2u3RrLt5BoLsZKBr+h0ZnFsA=,1,0,NaN,7,20120105,20170918
13,RoSfblbwJN/izEnFIVw8TgOpm8R/NEpUC84Oz/b32HQ=,15,33,female,3,20150915,20171019
14,N+dxmo1qvkKAlzYtcxGzjrqcpVyX9J7AMlXFuYASKuY=,1,0,NaN,3,20140412,20170815
15,vUzJAyFEudsnkWwfcLIKT5mJAV+uVRTW2uajCrghFwI=,13,20,male,3,20140410,20170427
16,Ev+ouoRTpAjrtxNVeThP6t9xnDG1puQaG28DvJ2db+A=,13,30,male,9,20070330,20170612
17,/NFMlPP8FvyxVLHcSA4af/BfbRvGXwD+IYpZqVylb7I=,1,0,NaN,7,20121228,20170930
18,XeAoaR5gMiy74l4HUhHt10o36U7VevuMZOymd0EWqD0=,1,0,NaN,4,20161224,20170614
19,v8+kU3kqYo9P8kIcuLrliJ/57jCTZG75cXvyYdagbhU=,1,0,NaN,9,20160923,20170925
20,+QyD+0xRgzi2552jFOFk5FfDJsqfe5D6xmHpHf6J5Bk=,1,0,NaN,4,20170124,20170127
21,2g1ydVe2XxKPTMf2P9BhFfZOUC0Kteti8KyMr6iVaj0=,5,29,male,4,20161124,20170808
22,IptzXjBNx4yZaetmolc/moHn2SYT2oZM7SX9mGyMKDo=,1,0,NaN,9,20161209,20161212
23,v1/E8gN8p5TFweTX3HAc4mm31LxqP6c1ZGGJiKyCuH4=,1,0,NaN,4,20170120,20170808
24,ed0hCzvhKVxHMIodLtgkzb1G4ryiet50rO/GE3W3pEA=,1,0,NaN,4,20161209,20161212

In [4]:
subm.head(25)

    id  target
0    0     0.5
1    1     0.5
2    2     0.5
3    3     0.5
4    4     0.5
5    5     0.5
6    6     0.5
7    7     0.5
8    8     0.5
9    9     0.5
10  10     0.5
11  11     0.5
12  12     0.5
13  13     0.5
14  14     0.5
15  15     0.5
16  16     0.5
17  17     0.5
18  18     0.5
19  19     0.5
20  20     0.5
21  21     0.5
22  22     0.5
23  23     0.5
24  24     0.5

In [5]:
song_info.head(30)

,song_id,name,isrc
0,LP7pLJoJFBvyuUwvu+oLzjT+bI+UeBPURCecJsX1jjs=,我們,TWUM71200043
1,ClazTFnk6r0Bnuie44bocdNMM3rdlrq0bCGAsGUWcHE=,Let Me Love You,QMZSY1600015
2,u2ja/bZE3zhCGxvbbOB3zOoUjx27u40cf5g09UXMoKQ=,原諒我,TWA530887303
3,92Fqsy0+p6+RHe2EoLKjHahORHR1Kq1TBJoClW9v+Ts=,Classic,USSM11301446
4,0QFmz/+rJy1Q56C1DuYqT9hKKqi5TUqx0sN0IwvoHrw=,愛投羅網,TWA471306001
5,QU8f6JR0/cwLGSqJX2XDVzFK0DxMaIUY15ALJXK7ziw=,Our Time,GBAYE1400079
6,O1Oj4CmnZhbHl7oyBaHSpGeu5gvcSmUydY3Awmv3uxk=,癢,HKUM70704066
7,Tr5R61AuEkN8UelOCzu09ZwQi7/HmP9sQmxf9rFngIg=,Aloha| E Komo Mai (Theme Song from Lilo & Stit...,USWD10423930
8,ie9l12ZYXEaP4evrBBUvnNnZGdupHSX5NU+tEqB1SDg=,每天愛你多一些,HKA610200010
9,6mICNlckUVGuoK/XGC7bnxXf5s2ZnkpFHShaGL/zM2Y=,你是你的,TWI431000103
10,BUQwTuzZ8GKEiHtFoI1hFcKRK1W3EEpfD+VLcIVkUzQ=,Guilty All The Same (feat. Rakim),USWB11400510
11,fuQO8mNakRgp0vDqDJbvorJvMcJMvSjldFKAz6g+27Y=,Steal My Girl,GBHMU1400159
12,oIkuw3YGuUhqJd8CMJxvBep4rEXXJxea71l1JO0EhfQ=,月亮惹的禍,TWB439808011
13,jAeBPAOGuLjjF81uYHVj8sayYH6VQhaHGPhTfq+u8O4=,什麼東西,TWF710800009
14,gB4Fu5VOaGR+E1ITkBnb4yU2SdZFW6Q+K/OHPAZhZJk=,雨水我問你,TWD970400025
15,uzWI7xZfL3gL2/B4ptZs0XfBuGC20ydak01SjhFuEtc=,如此美麗的妳,NaN
16,EXBuTr6J7UY6MDozwT/UDRVnmW0VGRVfeGBzrxVlX3k=,老鷹之歌,NaN
17,y2QmHXZMAhfVXwyQoimo5ZvMbNdS8qKCRRqKqU7izew=,離開,TWA451294108
18,isW4S3tqJo5Tce1AdM19n6TG53UQkBzyLFmb2QWK/G4=,Standing In The Rain,USAT21601931
19,OTKFDmheYsbqTCw2IEW4HDK3eckkrmXiQCWJWmgLSXI=,ONLY TIME (唯有時光),GBAHT0108626
20,r2+2/4YWEairmrZFCwJqTRfeIEYGS8oAW5FzPncfvGk=,Joy to the World,GBPS81528405
21,zXl5K/XMC/oPZ23YwKz36Y9fvdr7PeGv5D29QLBlpIs=,手語,TWK971201102
22,wSdWNC+BceQC4dBIgdNX7SGVXSFBhOCYTCWFtcvjmTw=,只要我長大,NaN
23,SBDpmvkE5OQHwA75K9liYM0JaLsIPQ822tW/vwR87AQ=,海芋戀,TWA530887311
24,8lGxKW1C1//LB32ChXt1tRFxD84VbA0Q9MlPJy96A8Y=,ラピュタの崩壊,JPTK08680213
25,gNLE0pDB/j9enPk37b1x//rZ1JMdJ3VYuxlQvDTeP0g=,You're Beautiful,CAM460437524
26,rb/HxIZV0w4GJn8k7Khc71nh5se+JIs1x2wdAkEYhKI=,保護你,TWL251507101
27,HCLMm7t3Wz4j3Bfc68yQ/kn32NQrM3OrfZmaxJIPoT8=,誰人愛我親像你,NaN
28,8NQymzoLhppIDdosaOzqicFTQ/Jmx73/hTSPsSqvp8g=,你是被抹去的那一段風景 (You are the Scene I Erased),TWS171500002
29,OG9PdbryZ35Qeikl+XsaS+t13LikbM11c0i+mCs3ukE=,真的嗎,TWA459801803

In [6]:
song.head(15)

,song_id,song_length,genre_ids,artist_name,composer,lyricist,language
0,CXoTN1eb7AI+DntdU1vbcwGRV4SCIDxZu+YD8JP8r4E=,247640,465,張信哲 (Jeff Chang),董貞,何啟弘,3.0
1,o0kFgae9QtnYgRkVPqLJwa05zIhRlUjfF7O1tDw0ZDU=,197328,444,BLACKPINK,TEDDY| FUTURE BOUNCE| Bekuh BOOM,TEDDY,31.0
2,DwVvVurfpuz+XPuFvucclVQEyPqcpUkHR0ne1RQzPs0=,231781,465,SUPER JUNIOR,NaN,NaN,31.0
3,dKMBWoZyScdxSkihKG+Vf47nc18N9q4m58+b4e7dSSE=,273554,465,S.H.E,湯小康,徐世珍,3.0
4,W3bqWd3T+VeHFzHAUfARgW9AvVRaF4N5Yzm4Mr6Eo/o=,140329,726,貴族精選,Traditional,Traditional,52.0
5,kKJ2JNU5h8rphyW21ovC+RZU+yEHPM+3w85J37p7vEQ=,235520,864|857|850|843,貴族精選,Joe Hisaishi,Hayao Miyazaki,17.0
6,N9vbanw7BSMoUgdfJlgX1aZPE1XZg8OS1wf88AQEcMc=,226220,458,伍佰 & China Blue,Jonathan Lee,NaN,3.0
7,GsCpr618xfveHYJdo+E5SybrpR906tsjLMeKyrCNw8s=,276793,465,光良 (Michael Wong),光良,彭資閔,3.0
8,oTi7oINPX+rxoGp+3O6llSltQTl80jDqHoULfRoLcG4=,228623,465,林俊傑 (JJ Lin),JJ Lin,Wu Qing Feng,3.0
9,btcG03OHY3GNKWccPP0auvtSbhxog/kllIIOx5grE/k=,232629,352|1995,Kodaline,Stephen Garrigan| Mark Prendergast| Vincent Ma...,Stephen Garrigan| Mark Prendergast| Vincent Ma...,52.0
10,HulM/OaHgD5kUyjNQjDUf8VZdsy7h4EJUIff79Cifwo=,272544,2157,D.L 羅時豐 (Daniel Lo),陳偉強,陳偉強,10.0
11,wypPzqFNdUJAqyBVxmFGaK4z7krUNWr5YqA0q0wi9eE=,254880,465,白安 (Ann),白安,白安,3.0
12,fAZLdfQaLG76a6Ei4alt1eSjBM9rshQkiQEC6+n+y08=,180871,726,Littlesong,Michael William Balfe,NaN,-1.0
13,tqBlH4r/q1Tf6C5+C6ucjGlLjMbfu5yjqB6ifRzy5dc=,257602,458,蔡旻佑 (Evan Yo),蔡旻佑,陳信延,3.0
14,an6EdIr+Z+KbqIVQiXn5PKkcXncefQ7hhWONseRuub4=,282697,359,Coldplay,Chris Martin| Guy Berryman| Jonny Buckland| Mi...,NaN,52.0

In [7]:
song['genre_ids'].fillna(' ',inplace=True)
song['composer'].fillna(' ',inplace=True)
song['lyricist'].fillna(' ',inplace=True)

In [8]:
#Analysing the Null Values in the Datasets

subm.isnull().sum(),mem.isnull().sum(),song_info.isnull().sum(),song.isnull().sum()

(id        0
 target    0
 dtype: int64,
 msno                          0
 city                          0
 bd                            0
 gender                    19902
 registered_via                0
 registration_init_time        0
 expiration_date               0
 dtype: int64,
 song_id       0
 name          0
 isrc       2702
 dtype: int64,
 song_id        0
 song_length    0
 genre_ids      0
 artist_name    0
 composer       0
 lyricist       0
 language       0
 dtype: int64)

In [9]:
train.head()

,msno,song_id,source_system_tab,source_screen_name,source_type,target
0,FGtllVqz18RPiwJj/edr2gV78zirAiY/9SmYvia+kCg=,BBzumQNXUHKdEBOB7mAJuzok+IJA1c2Ryg/yzTF6tik=,explore,Explore,online-playlist,1
1,Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=,bhp/MpSNoqoxOIB+/l8WPqu6jldth4DIpCm3ayXnJqM=,my library,Local playlist more,local-playlist,1
2,Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=,JNWfrrC7zNN7BdMpsISKa4Mw+xVJYNnxXh3/Epw7QgY=,my library,Local playlist more,local-playlist,1
3,Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=,2A87tzfnJTSWqD7gIZHisolhe4DMdzkbd6LzO1KHjNs=,my library,Local playlist more,local-playlist,1
4,FGtllVqz18RPiwJj/edr2gV78zirAiY/9SmYvia+kCg=,3qm6XTZ6MOCU11x8FIVbAGH5l5uMkT3/ZalWG1oo2Gc=,explore,Explore,online-playlist,1

In [10]:
test.tail()

,id,msno,song_id,source_system_tab,source_screen_name,source_type
2556785,2556785,XmA/cIkXJ8jZUfsUc4bBfJVWMMqmylnPW0WVkg/iz0s=,wJoWzZd7AL+qX9xZWZwRTzGRYg0Lxcl5Pe+9n5hZgAQ=,discover,Online playlist more,online-playlist
2556786,2556786,jvbujcxCExG0CrPShsEmZ6pePcHuRqru2OLEUw85iGk=,KCJ8BlSfRQRgB7EVuzFvg52AhR8m2fT032MzN5ewbEI=,discover,NaN,online-playlist
2556787,2556787,jvbujcxCExG0CrPShsEmZ6pePcHuRqru2OLEUw85iGk=,ySDsKJSnhFMESzC9mBhY0hnFEEBWDYx0FOMNcYDLb/A=,discover,NaN,online-playlist
2556788,2556788,jvbujcxCExG0CrPShsEmZ6pePcHuRqru2OLEUw85iGk=,WXH8kL8e+0H2jY+s2Y6FpHyyHdaMYV3b6yfDa3FAt9U=,discover,NaN,online-playlist
2556789,2556789,jvbujcxCExG0CrPShsEmZ6pePcHuRqru2OLEUw85iGk=,ftPDlhAywvcZX7ojE6F+9CDsC22UKX96iEr4W0ciPec=,discover,NaN,online-playlist

In [11]:
train.isnull().sum() , test.isnull().sum()

(msno                    0
 song_id                 0
 source_system_tab      67
 source_screen_name    576
 source_type            50
 target                  0
 dtype: int64,
 id                         0
 msno                       0
 song_id                    0
 source_system_tab       8442
 source_screen_name    162883
 source_type             7297
 dtype: int64)

In [12]:
#Remove the Unnecessary columns

train= train.drop(['source_system_tab','source_screen_name','source_type'],axis=1)
train.head()

,msno,song_id,target
0,FGtllVqz18RPiwJj/edr2gV78zirAiY/9SmYvia+kCg=,BBzumQNXUHKdEBOB7mAJuzok+IJA1c2Ryg/yzTF6tik=,1
1,Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=,bhp/MpSNoqoxOIB+/l8WPqu6jldth4DIpCm3ayXnJqM=,1
2,Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=,JNWfrrC7zNN7BdMpsISKa4Mw+xVJYNnxXh3/Epw7QgY=,1
3,Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=,2A87tzfnJTSWqD7gIZHisolhe4DMdzkbd6LzO1KHjNs=,1
4,FGtllVqz18RPiwJj/edr2gV78zirAiY/9SmYvia+kCg=,3qm6XTZ6MOCU11x8FIVbAGH5l5uMkT3/ZalWG1oo2Gc=,1

In [13]:
#renaming the Columns 
train.rename(columns={'msno':'user_id'},inplace=True)
train.head()

,user_id,song_id,target
0,FGtllVqz18RPiwJj/edr2gV78zirAiY/9SmYvia+kCg=,BBzumQNXUHKdEBOB7mAJuzok+IJA1c2Ryg/yzTF6tik=,1
1,Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=,bhp/MpSNoqoxOIB+/l8WPqu6jldth4DIpCm3ayXnJqM=,1
2,Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=,JNWfrrC7zNN7BdMpsISKa4Mw+xVJYNnxXh3/Epw7QgY=,1
3,Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=,2A87tzfnJTSWqD7gIZHisolhe4DMdzkbd6LzO1KHjNs=,1
4,FGtllVqz18RPiwJj/edr2gV78zirAiY/9SmYvia+kCg=,3qm6XTZ6MOCU11x8FIVbAGH5l5uMkT3/ZalWG1oo2Gc=,1

In [14]:
train.shape

(20000, 3)

# Processing the Dataset

In [15]:
a=train.merge(song,on='song_id')
a=a.drop(['song_length','language'],axis=1)
a.head()

,user_id,song_id,target,genre_ids,artist_name,composer,lyricist
0,FGtllVqz18RPiwJj/edr2gV78zirAiY/9SmYvia+kCg=,3Hg5kugV1S0wzEVLAEfqjIV5UHzb7bCrdBRQlGygLvU=,1,1259,Desiigner,Sidney Selby| Adnan Khan,
1,hZyOA+0yqClPLt6uIEndf8fG8szH/95eKMbaxLE5z30=,3Hg5kugV1S0wzEVLAEfqjIV5UHzb7bCrdBRQlGygLvU=,1,1259,Desiigner,Sidney Selby| Adnan Khan,
2,0LhkakIQDn36HZXI6ClQSO7W7jkpZAy+9MvYgPOZGrA=,skehue/d/R59G71dXYpntDwdjRRPlweN3JE8g40TgZU=,1,458,莊心妍,鄭建浩,鄭建浩
3,MofmAMt7P8LIcF4+LLlcjyIhYUzmv13L/LRwYFxiGYE=,skehue/d/R59G71dXYpntDwdjRRPlweN3JE8g40TgZU=,1,458,莊心妍,鄭建浩,鄭建浩
4,U9Z+N+szYGJHTPMn/C0V7yIyIC24fDI0RDRWChXATkg=,skehue/d/R59G71dXYpntDwdjRRPlweN3JE8g40TgZU=,0,458,莊心妍,鄭建浩,鄭建浩

In [16]:
a=a.merge(song_info,on='song_id').drop('isrc',axis=1)
a.rename(columns={'name':'song_name'},inplace=True)
a.head(10)

,user_id,song_id,target,genre_ids,artist_name,composer,lyricist,song_name
0,Eaq21N7ijazDjnqU5v1jjWewJopGxgZxkKr4GIq7JTs=,BwDDym6Tp7EnGudWBGJyjONZeX0/4ndu5PETiPWzav8=,1,458,楊乃文 (Naiwen Yang),黃建為,葛大為,離心力 (Centrifugal Force)
1,xOYfEnlbSceZPxSFui3yz91tAospqh+DrSS18Ix4GPE=,BwDDym6Tp7EnGudWBGJyjONZeX0/4ndu5PETiPWzav8=,0,458,楊乃文 (Naiwen Yang),黃建為,葛大為,離心力 (Centrifugal Force)
2,p/hZuEXU9ExH9LKkBfIueZUaNVX9SXQC3JXA8MiNWi4=,BwDDym6Tp7EnGudWBGJyjONZeX0/4ndu5PETiPWzav8=,1,458,楊乃文 (Naiwen Yang),黃建為,葛大為,離心力 (Centrifugal Force)
3,0m6KFYHZ0sEqA+UJ165welDpnMHu92JJYQ8sz1nChPU=,BwDDym6Tp7EnGudWBGJyjONZeX0/4ndu5PETiPWzav8=,1,458,楊乃文 (Naiwen Yang),黃建為,葛大為,離心力 (Centrifugal Force)
4,f8TJLlsG/vc/A+mdobHDauYO3QFAZCiY1fnmYooXsOk=,BwDDym6Tp7EnGudWBGJyjONZeX0/4ndu5PETiPWzav8=,1,458,楊乃文 (Naiwen Yang),黃建為,葛大為,離心力 (Centrifugal Force)
5,zQ54G6ixyiin3XFMoG5ibV9RSIkxpjnRLhCUXISAnf0=,BwDDym6Tp7EnGudWBGJyjONZeX0/4ndu5PETiPWzav8=,1,458,楊乃文 (Naiwen Yang),黃建為,葛大為,離心力 (Centrifugal Force)
6,gL8rPt5443Mn2vAVXbBuY7IB0haVmgkYC1VOK+p/PDM=,BwDDym6Tp7EnGudWBGJyjONZeX0/4ndu5PETiPWzav8=,0,458,楊乃文 (Naiwen Yang),黃建為,葛大為,離心力 (Centrifugal Force)
7,nH1t3DQT9gwRxkQ00vQ4tZHLsVkVHiz/FyYOdM3SbbA=,BwDDym6Tp7EnGudWBGJyjONZeX0/4ndu5PETiPWzav8=,1,458,楊乃文 (Naiwen Yang),黃建為,葛大為,離心力 (Centrifugal Force)
8,z/XkDTR6ji9UeOjMsxOARAKwMskoYBIZHigFqfQs3F0=,BwDDym6Tp7EnGudWBGJyjONZeX0/4ndu5PETiPWzav8=,1,458,楊乃文 (Naiwen Yang),黃建為,葛大為,離心力 (Centrifugal Force)
9,MKu7SuVv5V2iLS/UKKAqZ67uj9iAp62uQTqrGUOrRII=,BwDDym6Tp7EnGudWBGJyjONZeX0/4ndu5PETiPWzav8=,1,458,楊乃文 (Naiwen Yang),黃建為,葛大為,離心力 (Centrifugal Force)

# Data Cleaning

In [17]:
a['genre_ids'].value_counts()

465            48
458            22
444            21
2022            2
921             2
2122            1
139|125|109     1
359             1
                1
1609            1
726             1
437             1
451             1
Name: genre_ids, dtype: int64

In [18]:
a['genre_ids']=a['genre_ids'].str.replace('|',' ',regex=True)
a['genre_ids'].value_counts()

465            48
458            22
444            21
2022            2
921             2
2122            1
139 125 109     1
359             1
                1
1609            1
726             1
437             1
451             1
Name: genre_ids, dtype: int64